apiVersion: v1
kind: Service
metadata:
  labels:
    app: discourse
    environment: {{.Values.environment | quote}}
  name: discourse
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: discourse
  sessionAffinity: None
  type: ClusterIP