apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    environment: {{.Values.environment | quote}}
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP