apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis
    environment: {{.Values.environment | quote}}
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: bitnami/redis
        name: redis
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          limits:
            cpu: 1
            memory: 1Gi